const defaultEnv = require('./build/default')
const androidNativeEnv = require('./build/androidNative')
const androidBrowserEnv = require('./build/androidBrowser')
const chromedriver = require('chromedriver')

// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/

const config = {
	// An array of folders (excluding subfolders) where your tests are located;
	// if this is not specified, the test source must be passed as the second argument to the test runner.
	src_folders: ['./nightwatch/tests'],
	output_folder: './nightwatch/reports',

	// See https://nightwatchjs.org/guide/working-with-page-objects/
	page_objects_path: './nightwatch/page',

	// See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-commands
	custom_commands_path:  [
		'./nightwatch/custom/command'
	],

	// See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-assertions
	custom_assertions_path: [
		'./nightwatch/custom/assertion'
	],

	// See https://nightwatchjs.org/guide/#external-globals
	globals_path : './nightwatch/globals.js',
	
	test_settings: {
		default: defaultEnv({ chromedriver }),
		androidNative: androidNativeEnv({ chromedriver }),
		androidBrowser: androidBrowserEnv({ chromedriver })
	}
};

module.exports = config;